### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by Artlvns**

### CODE REVIEW

**Comment by dhaugli** [comment]
#### `terraform fmt` Failed

<details><summary><code>./Networking/main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=1.44.0"
+  version = "=1.44.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>
<details><summary><code>./VMs/Back-end/main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=2.0.0"
+  version = "=2.0.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>
<details><summary><code>./VMs/Front-end/main.tf</code></summary>

```diff
 provider "azurerm" {
-   version         = "=2.0.0"
+  version = "=2.0.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>
<details><summary><code>./main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=1.44.0"
+  version = "=1.44.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions1`, Working Directory: `.`*

**Comment by Artlvns** [comment]
All is working fine locally for each part of code. I have no Idea why format check fails in Actions..

**Comment by dhaugli** [comment]
#### `terraform fmt` Failed

<details><summary><code>./Networking/main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=1.44.0"
+  version = "=1.44.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>
<details><summary><code>./VMs/Back-end/main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=2.0.0"
+  version = "=2.0.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>
<details><summary><code>./VMs/Front-end/main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=2.0.0"
+  version = "=2.0.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>
<details><summary><code>./main.tf</code></summary>

```diff
 provider "azurerm" {
-  version         = "=1.44.0"
+  version = "=1.44.0"
 
   subscription_id = var.subscription_id
   client_id       = var.client_id
```

</details>

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions1`, Working Directory: `.`*

**Comment by dhaugli** [comment]
#### `terraform init` Failed

```

Initializing the backend...

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.

```

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions2`, Working Directory: `.`*

**Comment by dhaugli** [comment]
#### `terraform init` Failed

```

Initializing the backend...

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.

```

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions2`, Working Directory: `.`*

**Comment by dhaugli** [comment]
#### `terraform init` Failed

```

Initializing the backend...

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.

```

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions2`, Working Directory: `.`*

**Comment by dhaugli** [comment]
#### `terraform init` Failed

```

Initializing the backend...

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.

```

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions2`, Working Directory: `.`*

**Comment by dhaugli** [comment]
#### `terraform init` Failed

```

Initializing the backend...

Error: Required token could not be found

Make sure you configured a credentials block for app.terraform.io in your CLI
Config File.

```

*Workflow: `Terraform GitHub Actions`, Action: `hashicorpterraform-github-actions2`, Working Directory: `.`*

**Pull request merged**
